name: env-var-demo

on: workflow_dispatch

env:
  TRIGGER: github.event_name

jobs: 
  check_pull_push_request:
    runs-on: ubuntu-latest
    steps: 
      # 1er job pr dire PUSH
      - name: "PUSH"
        if: ${{ env.TRIGGER != 'push' }}
        run: echo "c'est un push!"
      - name: "PULL_REQUEST"
        if: ${{env.TRIGGER == 'pull_request'}}
        run: echo "c'est une pull request!"