name: trigger_event2

on:
  pull_request:
    types:
      - closed


    # if: ${{github.event_name == 'push' }} 


jobs:
  check_pull_request_merged:
    if: ${{github.event.pull_request.merged == true}}
    runs-on: ubuntu-latest
    steps:
      - name: merged
        run: echo "The PR was merged"