name: trigger_event

on:
  issues:
    types:
      - opened

jobs: 
  check_issue_created:
    runs-on: ubuntu-latest
    steps: 
      # 1er job pr tester
      - name: "afficher issue"
        run: echo "issue créée!"
  